apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: eShopOnWeb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshopweb
  template:
    metadata:
      labels:
        app: eshopweb
    spec:
      containers:
      - name: eshopweb
        image: ddeastacr.azurecr.io/dd-eshopweb:latest
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 80
